#server
app.name=complaint-manage
server.type=${server.type}
server.port=${server.port}
server.debug=true
server.connection-timeout=1000
user-profile-api.group=${user-profile-api.group}

spring.profiles.active=@profiles.active@

# pc\u670D\u52A1\u5BF9\u5916\u7684 group
cis.dubbo.group=${cis.dubbo.group}
dubbo.group=${dubbo.group}
dubbo.group.cis=${dubbo.group.cis}
dubbo.group.store=${dubbo.group.store}
dubbo.group.upload=${dubbo.group.upload}
dubbo.group.eiam=${dubbo.group.eiam}
# \u8C03\u7528\u5916\u90E8\u670D\u52A1\u9ED8\u8BA4\u7684 group
dubbo.group.outer=${dubbo.group.outer}
dubbo.group.nr=${dubbo.group.nr}
dubbo.group.customer=${dubbo.group.customer}
dubbo.group.warranty=${dubbo.group.warranty}
dubbo.group.file=${dubbo.group.file}
dubbo.group.message=${dubbo.group.message}
dubbo.group.club=${dubbo.group.club}
dubbo.group.clue=${dubbo.group.clue}
dubbo.group.delivery=${dubbo.group.delivery}
dubbo.group.utility=${dubbo.group.utility}
order.dubbo.group=${order.dubbo.group}
dubbo.protocol.id=${dubbo.protocol.id}
dubbo.protocol.name=${dubbo.protocol.name}
dubbo.protocol.port=${dubbo.protocol.port}
dubbo.registry.address=${dubbo.registry.address}
dubbo.config-center.address=${dubbo.config-center.address}
dubbo.metadata-report.address=${dubbo.metadata-report.address}
nacos.config.addrs=${nacos.config.addrs}
youpin.log.group=${youpin.log.group}
dubbo.job.group=${dubbo.job.group}
log.path=${log.path}
MaxHistory=120
talos.topic=${talos.topic}
talos.sendpoint=${talos.sendpoint}
talos.access.key=${talos.access.key}
talos.access.secret=${talos.access.secret}
app.nacos=${app.nacos}
spring.redis.host=${spring.redis.host}
spring.redis.port=${spring.redis.port}
spring.redis.password=${spring.redis.password}

# bi\u5E93\u914D\u7F6E
spring.datasource.mysql.write.druid.url=${spring.datasource.mysql.write.druid.url}
spring.datasource.mysql.write.druid.username=${spring.datasource.mysql.write.druid.username}
spring.datasource.mysql.write.druid.password=${spring.datasource.mysql.write.druid.password}

spring.datasource.mysql.write.druid.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.mysql.write.druid.initialSize=30
spring.datasource.mysql.write.druid.maxActive=50
spring.datasource.mysql.write.druid.minIdle=20
spring.datasource.mysql.write.druid.maxWait=20000
spring.datasource.mysql.write.druid.removeAbandoned=true
spring.datasource.mysql.write.druid.removeAbandonedTimeout=300000
spring.datasource.mysql.write.druid.timeBetweenEvictionRunsMillis=60000
spring.datasource.mysql.write.druid.minEvictableIdleTimeMillis=1800000
spring.datasource.mysql.write.druid.validationQuery=SELECT 1
spring.datasource.mysql.write.druid.testWhileIdle=true
spring.datasource.mysql.write.druid.testOnBorrow=true
spring.datasource.mysql.write.druid.testOnReturn=false
spring.datasource.mysql.write.druid.init=true
spring.datasource.mysql.write.druid.filters=stat,wall,log4j
spring.datasource.mysql.write.mybatis.configuration.map-underscore-to-camel-case=true

# ----- print sql config -----
spring.datasource.druid.filter.slf4j.enabled=true
spring.datasource.druid.filter.slf4j.statementPrepareAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementCreateAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementExecuteQueryAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementExecuteAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementParameterSetLogEnabled=false
spring.datasource.druid.filter.slf4j.statementCloseAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementExecuteBatchAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementExecuteUpdateAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementPrepareCallAfterLogEnabled=false
spring.datasource.druid.filter.slf4j.statementExecutableSqlLogEnable=true
spring.datasource.druid.filter.slf4j.statementLogEnabled=true
spring.datasource.druid.filter.slf4j.statementSqlPrettyFormat=false

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
### management
management.server.port=12501
management.endpoints.web.exposure.exclude=mappings,threaddump,heapdump
management.endpoints.web.exposure.include=metrics,prometheus,health
management.endpoint.health.show-details=always
management.metrics.tags.appName=${app.name}
management.metrics.tags.environment=${server.type}

proretail.filter.service.enabled=true
proretail.filter.provider.enabled=true
proretail.filter.p95count.enabled=true
proretail.filter.faker.enabled=true

#key.center.host=${key.center.host}
#key.center.sid=${key.center.sid}

proretail.account.enabled=true
proretail.account.eiam.dubbo.group=${dubbo.group.nr}
proretail.account.maindata.dubbo.group=${dubbo.group.nr}
proretail.account.user.profile.dubbo.group=${dubbo.group.profile}

proretail.project.id=${proretail.project.id}
proretail.project.name=${proretail.project.name}
template.file.path=${template.file.path}
job.upc.project.id=${job.upc.project.id}
job.upc.delivery.project.id=${job.upc.delivery.project.id}
job.admin.addresses=${job.admin.addresses}
job.accessToken=${job.accessToken}
job.executor.appname=${job.executor.appname}
job.executor.ip=${job.executor.ip}
job.executor.address=${job.executor.address}
job.executor.port=${job.executor.port}
job.executor.logpath=/home/work/log/complaint-manage/jobhandler
job.executor.logretentiondays=7
temp.directory=${temp.directory}
# comment system http config
#xiaomi.mall.authKey=${xiaomi.mall.authKey}
#xiaomi.mall.host=${xiaomi.mall.host}

mail.address=${mail.address}
mail.type=${mail.type}

# BPM??
dubbo.nr-bpm.appId=${dubbo.nr-bpm.appId}
dubbo.nr-bpm.appKey=${dubbo.nr-bpm.appKey}

dubbo.application.name=${app.name}

#{sentinel\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD}
spring.application.name=${app.name}
# \uFFFD\uFFFD\u013F\u05E2\uFFFD\uFFFD\uFFFDsenbtinel\uFFFD\u01F7\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
spring.cloud.sentinel.eager=true
# sentinel dashboard \uFFFD\uFFFD\uFFFD\uFFFDsentinel dashboard\uFFFD\u0137\uFFFD\uFFFD\u02B5\uFFFD\u05B7
spring.cloud.sentinel.transport.dashboard=http://sentinel.test.be.mi.com
# sentinel\uFFFD\u037B\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05BE\uFFFD\uFFFD\uFFFD\u013F\u00BC
spring.cloud.sentinel.log.dir=${log.path}/sentinel-client
# sentinel datasource nacos
#\uFFFD\uFFFD\uFFFD\u0639\uFFFD\uFFFD\uFFFD
spring.cloud.sentinel.datasource.ds1.nacos.server-addr=${app.nacos}
spring.cloud.sentinel.datasource.ds1.nacos.dataId=${app.name}-flow-rules
spring.cloud.sentinel.datasource.ds1.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds1.nacos.rule-type=FLOW
#\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD
spring.cloud.sentinel.datasource.ds2.nacos.server-addr=${app.nacos}
spring.cloud.sentinel.datasource.ds2.nacos.dataId=${app.name}-degrade-rules
spring.cloud.sentinel.datasource.ds2.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds2.nacos.rule-type=DEGRADE



threadpool.config=${threadpool.config}
MiApi.autoUpdate=${MiApi.autoUpdate}


dubbo.group.maindata=${dubbo.group.maindata}

# mock?????
monemock.mock.server.url.prefix=http://mock-server.test.mi.com/dubbo/mock
# ???????????????????????false
#MiApi.autoUpdate=true

data.go.url=${data.go.url}

# \u4E2D\u53F0\u6587\u4EF6\u4E0A\u4F20\u7684\u914D\u7F6E
upload.api.url=${upload.api.url}
upload.api.appkey=${upload.api.appkey}
upload.api.projectId=${upload.api.projectId}

#upc\u7CFB\u7EDF\u7B7E\u53D1\u7684appId\uFF0C\u540CX5\u534F\u8BAE\u76F8\u540C
dubbo.nr-upload-center.appId1=${upc.appId}
#upc\u7CFB\u7EDF\u7B7E\u53D1\u7684appKey\uFF0C\u540CX5\u534F\u8BAE\u76F8\u540C
dubbo.nr-upload-center.appKey1=${upc.sign-key}

proretail.keycenter.auto.decrypt.open=true
proretail.keycenter.auto.decrypt.list=spring.redis.password,spring.datasource.mysql.write.druid.password\
  ,job.accessToken,upload.api.appkey,upc.sign-key,car.rocketmq.accessKey,car.rocketmq.secretKey

proretail.keycenter.config.sid=${proretail.keycenter.config.sid}
proretail.keycenter.config.host=${proretail.keycenter.config.host}
proretail.keycenter.auto.decrypt.log.open=${proretail.keycenter.auto.decrypt.log.open}

dubbo.group.orderId=${dubbo.group.orderId}
dubbo.group.userquery=${dubbo.group.userquery}

user.query.access.key=${user.query.access.key}
user.query.secret.key=${user.query.secret.key}

car.label.tagDefId=${car.label.tagDefId}

kc.sid=${kc.sid}

dubbo.nr-upload-center.appId=${dubbo.nr-upload-center.appId}
dubbo.nr-upload-center.appKey=${dubbo.nr-upload-center.appKey}
dubbo.nr-upload-center.projectId=${dubbo.nr-upload-center.projectId}
dubbo.nr-upload-center.url=${dubbo.nr-upload-center.url}

rocketmq.nameserver=${rocketmq.nameserver}
car.order.status.change.topic=${car.order.status.change.topic}
car.complaint.manage.consumer=${car.complaint.manage.consumer}
car.rocketmq.accessKey=${rocketmq.accessKey}
car.rocketmq.secretKey=${rocketmq.secretKey}

car.org.change.topic=${car.org.change.topic}

dubbo.bpm.group=${dubbo.bpm.group}



rocketmq.topic.nr_car_soc_operate_work_order=${rocketmq.topic.nr_car_soc_operate_work_order}
rocketmq.producer.group=${rocketmq.producer.group}

MiApi.openApacheAnno = true
MiApi.opUser=auto
MiApi.updateMsg=auto
pc.main.car.maintenance.url=${pc.main.car.maintenance.url}
pc.main.customer.service.url=${pc.main.customer.service.url}
lark.app.id=${lark.app.id}
lark.app.secret=${lark.app.secret}
deliverHost=${deliverHost}
