#server
app.name=complaint-manage
cat.biz.name=complaint-manage-online
server.type=online
server.port=8080
server.debug=true
server.connection-timeout=1000
dubbo.group=car_online
dubbo.group.outer=online
dubbo.group.nr=product
dubbo.group.profile=production
dubbo.group.customer=pro
dubbo.group.warranty=car_online
cis.dubbo.group=car_online
dubbo.group.file=online
dubbo.group.message=car_online
dubbo.protocol.id=dubbo
dubbo.protocol.name=dubbo
dubbo.group.eiam=car_online
dubbo.group.club=online
dubbo.group.clue=car_online_app
dubbo.group.delivery=car_online
dubbo.group.utility=car_online
dubbo.job.group=car_online
dubbo.bpm.group=production
order.dubbo.group=car_online
dubbo.protocol.port=-1
dubbo.config-center.address=nacos://mione-config-nacos.api.xiaomi.net:80
dubbo.registry.address=nacos://mione-nacos.api.xiaomi.net:80
dubbo.metadata-report.address=nacos://mione-config-nacos.api.xiaomi.net:80
nacos.config.addrs=mione-config-nacos.api.xiaomi.net:80
app.nacos=mione-config-nacos.api.xiaomi.net:80

youpin.log.group=online
log.path=/home/work/log

# MySQL
spring.datasource.mysql.write.druid.url=jdbc:mysql://cn.b2c.vehicle-bizdev.car-complaint-manage.mysql.srv:6405/car_complaint_manage?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
spring.datasource.mysql.write.druid.username=car_complainv2_wn
spring.datasource.mysql.write.druid.password=GDBQBQxdLYVXUhxRqq4-UMCPs2LtLaKmti9WhG1_ezs4saxmv1yBaVk9MFQLHpj8g4UYEpnlwydreUSZux1wKcQTw50iARgQMbjhZuK4TsyKYhuayeRk6hgUHdCS8FQbh9O4SAZhpHaG110JwmcA

talos.topic=cnzone_newretail_pro_retail_online
talos.sendpoint=http://cnbj4-talos.api.xiaomi.net
talos.access.key=GCBu8+u2FRkrgqneMTJAThqDr+mIqyvqhE7ycaWByfvkaRgSlRg/OzyES0ufETTpuUX7rboBGBD2tewW9dxBbJiHoIfOR71cGBQxxWfbr8jdASLhuu840Xu0z7fGvgA=
talos.access.secret=GDCfyK3Hp0b8yNcm6SGUwuFDPw4dzkUAxW9h8w7L9M0vNA5q1EgikDjaRadpps1vhPgYEriuFCQ2c0EUiewBaWoHMHOsARgQS90+CVG8QHWIBaqtTyoU/RgUFtgpb1EnobFLV/oDrts1J9szWVUA

spring.redis.host=cache01.b2c.srv
spring.redis.port=5100
spring.redis.password=GDBfs19K/YfH0B59M06VctqLsS4YVFKDrPc5oKteTNiKdxqAeoa5d3XaPFhQEyMfu2IYEo8SU/MhjkoKq5X696JqAVMzARgQgwTNugt9QmCyYdrU/RjD/RgUrOL/Yl8UdJVL4RLe13s1Bn0MIu0A

shopApi.url=http://karos.shopapi.b2c.srv
shopApi.appkey=GDCIXhR/GZarmvMDMYEAIwBAUSg+q8cXZfG0lJJZQ6UcrfD7w8guEjE+0+OWL7PfY3kYEriuFCQ2c0EUiewBaWoHMHOsARgQWOX4ZoF+QOGNVgHjUs/M9RgUPbxRfGGwCLUmiCCaj1PNsUJINR4A
shopApi.clientId=180100031052
shopApi.appid=XM1003
workbench.app.id=3568165248000084
workbench.app.key=GDB/b1iW/Ka/QGjDmmqg1gJdJtYnPssqMSx54GA9yyCltMY7ltZKqgwa4wo21JTq20QYEmXTSYh9LkoFuv8lV2+dzkrKARgQSAmRaKYgQd+tIP36kP47zhgUmk+S6FwbtaXB+Wi8JF9aiF0qj2cA
workbench.policycenter.domain.url=http://mission-center.be.mi.com

#key.center.host=127.0.0.1
#key.center.sid=proretail-app
sentry.dsn=https://1e1195f53a754482b125f3eb175e76de@sentry.d.xiaomi.net/578

sentinel.transport.dashboard=http://sentinelc3.mi.bilibili.network

sApi.url=http://nr-api.d.mi.com
sApi.clientId=386816524800002
sApi.appSecret=GDDgLgAVuicmOWL7DvvkCXL3LSTVjbC4RshRgRYnQSw7vEPYShwMQKFV3aDY0A5Kyz0YEoDU+SIgUUJfvu7YBc8cDZf/ARgQN5tBPMDYT9S1esU4W9DYpxgUnjGig4DgzPxNvAmgEfVq7aXYScwA

zookeeper.host=c3
iauth.sdk.app.appId=391320093503655936
iauth.sdk.app.appKey=GCCcUTkaxrLZosfu0xn6f6ApB2IOyYFPPFrgb839rwoYFRgSNXSDG0HaRs+RDDH5Eb5Xc1kBGBAZ9I+WgeFAIouyEriu+kOeGBTHtMMyF0TGC9EAGog1JynC88D79gA=

incentiveOverviewBeginMonth=202012

comment.server.url=http://comment.service.b2c.srv
comment.server.auth=GFA4XZQVe9ZYwSMxtbaX1JIPUswqprsbBROoj9lSNKw/XvQpykuz4Mp2YSlOhmP2bTUzNz51RB2iHQHJ4HG+ICfWRJd4T4ddAAzXbWYv4GX9DBgSAe30UfoiST+wtg3M9yjw+N0BGBBaDcu5J/5H64N2+hD2f1s/GBT4aqKWP7BNe042UkRsFhGQoj9MKQA=

user-profile-api.group=production

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://xxljob.proretail.be.mi.com/xxl-job-admin
### xxl-job, access token
xxl.job.accessToken=GDAT3p5NPta/M6ipBqTblm+KHrCQ9CsYdDqS+6rrUwJRpKGo/CxZtnt2ffY7Xic050wYEriuFCQ2c0EUiewBaWoHMHOsARgQQGs1sdNBTo2vEU0n9caFORgUjYaxSkuZpJzR5DaovN0HaNNIqWIA
### xxl-job executor appname
xxl.job.executor.appname=service-base-business-online
xxl.job.executor.port=27863
### xxl-job executor log-path
xxl.job.executor.logpath=/home/work/log/xxl-job/
temp.directory=/home/work/

sale.service.url=http://xms.be.xiaomi.com
sale.service.appkey=GDDCfymsNfrsIAUd+dDxm0tW9pPXj/YNbrWO3nMvD6IBogbaXk5hZsSzAq1eytbBcNAYEgmnX8ZoWE9ihuj7aECoKWHqARgQ3XEanoN/Sx2lcrYBhW6mpxgU58q2sfYa4tV4d/RO9/fB3JAdTvEA
sale.service.appid=lst_order

job.upc.project.id=773
job.upc.delivery.project.id=175
job.admin.addresses=http://nr-job.be.mi.com
job.accessToken=GCC59u4OV5IARBt8T5QtnNsDHBsWjMRx4Sfq9FFiOC2AXBgSr591r9eZSW+1UNCAzstObK0BGBDVSW1MfhhDqagy8HLHy2rUGBT7aKW5slLdav8lRf0nTGe9sn6GGgA=
job.executor.appname=complaint-manage
job.executor.ip=
job.executor.address=
job.executor.port=9991
job.executor.logpath=/home/work/log/complaint-manage/jobhandler
job.executor.logretentiondays=7
proretail.project.id=10
proretail.project.name=complaint-manage
template.file.path=resources/template
job.stock.jobKey=stockJobHandlerJob
job.stock.jobHandler=stockJobHandler

## message center
message.center.url=https://newretail-message.d.mi.com
message.center.source=retail
message.center.secret=GCAW6bfPjibWNryaKM7xxra2CrMXLW3VjQAK6eBlbnbVJRgSo3geWymgTdehLLItHqr+XZYBGBDgLtGuEK9LHL0xdppa3z/KGBQhk2kYJTRd22h/btah2rlAwpcoyQA=
message.center.export.center.account.id=7
## upload
qiankun.upload.profile=c4
## upload by upc appId
qiankun.upload.appId=xm-yp-upc-0010
# # comment system http config
xiaomi.mall.authKey=GFAhuWgXrAMyVRfMhtgeJMSpUHn1i0P8Ha7yCw8AyEnP4+YYMy5ns6MCxAuMKimok2vCsuak/A7xsrbKNB5Q7zHooyxR3MuPTtrRw0qyTFGK8RgSIh8eHiB8SaqWGlqcgfpuFvABGBDzGTpLBI9PbKK2/2eUxVZBGBTotvorXmrw3GXovOLq1LL+jVWjIgA=
xiaomi.mall.host=http://comment.service.b2c.srv

## converged cloud for mail
mail.address=https://mail.d.xiaomi.net
mail.type=45

dubbo.group.maindata=online
dubbo.group.cis=car_online
dubbo.group.store=car_online
dubbo.group.orderId=online
dubbo.group.userquery=car_online

data.go.url=http://datago.be.mi.com

upload.api.url=https://nr-upload.m.mi.com/
upload.api.appkey=GDBRGjvV6maWgbs5VUBGGszL3C1qAf7LePU2WFUwCpxO2zp3iHQagZ0DXjb99lBwWmYYEljnXW4JWEyOme7kQ+QPFZh1ARgQl0hZg6lXS1egGC06V3CW+xgUDipzqlcIpkpgfWcZ3OOvZB1RClMA
upload.api.projectId=10

dubbo.group.upload=online
dubbo.eiam.group=car_online

threadpool.config=find:pro
MiApi.autoUpdate=true

#X5??????
upc.sign-key=GDBRGjvV6maWgbs5VUBGGszL3C1qAf7LePU2WFUwCpxO2zp3iHQagZ0DXjb99lBwWmYYEljnXW4JWEyOme7kQ+QPFZh1ARgQl0hZg6lXS1egGC06V3CW+xgUDipzqlcIpkpgfWcZ3OOvZB1RClMA
#??id
upc.appId=xm-yp-upc-0010

car.label.tagDefId=522

user.query.access.key=complaint_manange
user.query.secret.key=GCA533JYbpYKRLbN85hOMooLJG5Ph6Bp0J3iBX7OA5AtmBgSc/B777xPTgiCPaExMFTsc38BGBCXq9LPxttDD7bPOW3cXvhWGBR1aEgMVuX6TL40zIWc5lLOmfaSjAA=

#upload
dubbo.nr-upload-center.appId=xm-yp-upc-0192
dubbo.nr-upload-center.appKey=5bd6abce7534415ed355cbc055a0fe33
dubbo.nr-upload-center.projectId=192
dubbo.nr-upload-center.url=https://nr-upload.m.mi.com

rocketmq.nameserver=cnbj1-rocketmq.namesrv.api.xiaomi.net:9876
car.order.status.change.topic=nr_message_car_mrs_order_status_change_topic
car.complaint.manage.consumer=complaint_manage_consumer
rocketmq.accessKey=GCBgprFaOtzL+ITIkhWbJF7DbmVDW7EdSYc7OJGVB6Tv2hgSP1mcTea7QkijjmLWg4HIgyMBGBCy1B3J05lPqIUol4+UvjUKGBQB+si+dgAs13LYwzDnFtVEshpsAgA=
rocketmq.secretKey=GDBh54tFMtb6JI9d84uo7dLx7zN477zm0ay6P9QyEj3HjltMGsFtrx+We9ix059vCc0YEsxpQktx2k/NvNEQQQR27MdpARgQrcYxz1sFRHCpJVdHXzgWJxgU5RpuCcT3wq+aG7Isor3aMnpfMNsA

rocketmq.topic.nr_car_soc_operate_work_order=nr_car_soc_operate_work_order
rocketmq.producer.group=car_complaint_manage_producer_group

car.org.change.topic=store_digitization_car_pro

kc.sid=proretail-app

# 配置
proretail.keycenter.config.sid=proretail-app
# miline部署/mione部署
proretail.keycenter.config.host=127.0.0.1
#proretail.keycenter.config.host=172.17.0.1
proretail.keycenter.auto.decrypt.log.open=false
proretail.keycenter.auto.decrypt.youpinlog.open=true
pc.main.car.maintenance.url=https://v.be.mi.com/main-car-maintenance/
pc.main.customer.service.url=https://kefu.v.mi.com/main-customer-service/
lark.app.id=cli_a774b4e64ab85062
lark.app.secret=GDBzkV7XAj6e/dWeVBXkVaiTCN4U7wqDJ7X/dwg7HQwNWTfdAcHeOcqXD279OjCcC/QYEtFtLKbmfUakm6Mls4XZZPHHARgQs6cPry2UQXqVKJdVJ04zdBgUD8Dsd2NQm2CEXEryz8KOVLCjXRMA
#BPM??
dubbo.nr-bpm.appId=
dubbo.nr-bpm.appKey=
deliverHost=https://v.mi.com
