#server
app.name=complaint-manage
cat.biz.name=complaint-manage-dev
server.type=dev
server.port=8081
server.debug=true
server.connection-timeout=1000
dubbo.group=dev
dubbo.group.outer=staging
dubbo.group.nr=staging
dubbo.group.profile=staging
cis.dubbo.group=staging
dubbo.group.customer=test
dubbo.group.warranty=staging
dubbo.group.file=staging
dubbo.group.message=staging
dubbo.group.club=staging
dubbo.group.clue=staging
dubbo.group.delivery=staging
dubbo.group.utility=staging
dubbo.protocol.id=dubbo
dubbo.protocol.name=dubbo
dubbo.job.group=staging
dubbo.bpm.group=test
order.dubbo.group=staging
dubbo.protocol.port=-1
dubbo.config-center.address=nacos://mione-staging-nacos.api.xiaomi.net:80
dubbo.registry.address=nacos://mione-staging-nacos.api.xiaomi.net:80
dubbo.metadata-report.address=nacos://mione-staging-nacos.api.xiaomi.net:80
nacos.config.addrs=mione-staging-nacos.api.xiaomi.net:80
app.nacos=mione-staging-nacos.api.xiaomi.net:80

youpin.log.group=staging
log.path=/tmp



talos.topic=cnzone_newretail_common_test
talos.sendpoint=http://staging-cnbj2-talos.api.xiaomi.net
talos.access.key=GCBDW1Vfx0CbBS7++W14AN3xqs6XjWvj6AmyOEtyLvTYOxgSCouMKKItTqG/NBb+8GjhyWb/GBAZTrMCUBdHA7H6zIfOexF6GBQDrCXySVoaHAxZa8h7Bbs0vdc/mQA=
talos.access.secret=GDCtbo8VGIWPoezit4NQPCJT8nCu4e4shbZKJlvr9lqphk+gG0sS9SbRB75hOD7v8CMYEjpxxHinNEj3hKsj+Wm6C7z9/xgQbCnVwCRYRNaEuHVHDMO1lBgUR/O7fuIO/jlLVUIzNK3QVKDbmaQA

spring.redis.host=wcc.cache01.test.b2c.srv
spring.redis.port=22122
spring.redis.password=GDDLFwo+gchAgweaMRnAep1Tuch6E94nbh72lCixreKZMa+zT/yqFNK3X+vKhbyvdLoYEjtk6uqweEPavTWVQcjrnZGv/xgQaf1br/+DTyGHZKyqc+cD+xgUyuUXA9LZR66Kbl0gfQiAc/RrpugA

#?????
spring.datasource.mysql.write.druid.url=jdbc:mysql://gaea.test.mysql02.b2c.srv:13406/car_complaint_manage?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
spring.datasource.mysql.write.druid.username=car_complainv39_wn
spring.datasource.mysql.write.druid.password=GDDGVsba9Oe4kh4bD9RG4tvYcyXE3RgZwizVkG9eON9ACr0JdstWG45FC1hoz8C-5P4YEuY9u4o2q0Cgs3i7U1I02oXM_xgQOBIDNuVSRYyG55O9b1x-9xgUU-B4R22MAAilhUc0OVuUSFKf2bMA

workbench.app.id=1234567890
workbench.app.key=GDAPQahK2279o2JTwh5WWHLu6ZuG1QJ9SwVsx0nrMQ3lZh3kumgTIaNfBdV5bbJKhOMYEq6bu4IOOkPfr/7FQvSNNj00/xgQx0TVHxbFR9mqbNffhX2AORgUmL2Ur2f+3iE7KvnelgjzzGyF7xQA
workbench.policycenter.domain.url=http://mission-center.test.mi.com
shopApi.url=http://karos.shopapi.test.b2c.srv
shopApi.appkey=GDBUtu6iRyJ0YWRss36an+vNtWF0rHaEciuli66SK+8eh0NcQaIPZS7pwzUFFZPWaSsYEjpxxHinNEj3hKsj+Wm6C7z9/xgQ6Mvm0ZOASCyYdGmzBi/MoBgURpcBfjKA3ULwdmchjl93+5EoWIwA
shopApi.clientId=180100031052
shopApi.appid=XM1003

#key.center.host=
#key.center.sid=
sentry.dsn=https://6068b4c49d4f4e8db9a6da821da4606d@sentry.d.xiaomi.net/577

sentinel.transport.dashboard=http://sentinel.mi.bilibili.network

sApi.url=http://s-api.test.mi.com
sApi.clientId=5868486989668580
sApi.appSecret=GDA9+73rlvnbu85Rw9Ewr2JmW/TPHuAuvs/mkw/YTDqqAe4uwkxfOG97QYAqjgCgt6gYEks+n2dRVUY5gHZqd28fkmf7/xgQM4szlwIySb6UXFgimT0viRgUmELQKQRLTVTncek987Yt3uyRbu4A

iauth.sdk.app.appId=390716305805807616
iauth.sdk.app.appKey=GCBp4tE2R/9ABjCvcwahd36MHhDAWSYyXpSmdy+HbjpbPhgSBVVQChUtRY6v7FGeXk+4b0L/GBAX8xTvI5FGjKhA0fuKeveFGBQtZbmn1rrIr5Zt8RVgC7Ieu56a5AA=
zookeeper.host=staging

incentiveOverviewBeginMonth=202012

comment.server.url=http://comment.test.b2c.srv
comment.server.auth=GEAa+eDCqItEj+WJYsNhE7+3UCsmX+YsUz1XM2QLBV1ZJ/uAxRgyBTsehSR9rY7cHrmYkOoKd4Nkp5+EVJf76xWGGBId1K5Of1FHYb6vRK36yNLP1P8YEGs0b8n+0kyouUR1kqcR9RQYFEYXp/JfpAndGMLKtW97HgjRIa8JAA==

user-profile-api.group=dev

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://xxljob.test.mi.com/xxl-job-admin
### xxl-job, access token
xxl.job.accessToken=GDDprEp7v0jPR+76Q9VzVTIwtmQODjlHUvxPJQ1XFa8wocF7+UM6s68kkf4UrKEMXAAYEuL7Mu6h/0ubpjfsixwFceuV/xgQXZFIe2uyR62g8pTB7m2j3hgUgfWLlQMfFq81Ulzal8LmBzU3cO0A
### xxl-job executor appname
xxl.job.executor.appname=service-base-business-dev
xxl.job.executor.port=9999
### xxl-job executor log-path
xxl.job.executor.logpath=~/log/xxl-job/
temp.directory=/tmp/

sale.service.url=http://xms.be.test.xiaomi.com
sale.service.appkey=GDDX5oLZovzi8R/s3wquvJG/t2T8bMxwrFJTnhhyRHRYoJJpWLdV1o5E3W3aIpAJ4pQYEnYfaOEmpUeMtFv6DLi538SH/xgQOXEpnZPnSvqFZs49c8d4VRgU4yeI1xY2dwVp5IZGkXNNqGLIf34A
sale.service.appid=lst_order

job.upc.project.id=773
job.upc.delivery.project.id=731
job.admin.addresses=http://nr-job.test.be.mi.com
job.accessToken=GCBARSg+kHt2OlwzWZTOUafEDPvXEJzbCEuQTDtwu2jbJRgSPGNb15nZSt2SXXrx8hTE++//GBA82vldvPxALqxsELuVx5t0GBRmVezWK2m6Ialw11oKvn+vkQrtzwA=
job.executor.appname=complaint-manage
job.executor.ip=
job.executor.address=
job.executor.port=9991
job.executor.logpath=/home/work/log/complaint-manage/jobhandler
job.executor.logretentiondays=7
proretail.project.id=18
proretail.project.name=complaint-manage
template.file.path=resources/template
job.stock.jobKey=stockJobHandlerJob
job.stock.jobHandler=stockJobHandler

## message center
message.center.url=https://newretail-message.test.mi.com
message.center.source=nr
message.center.secret=GCDBg4adDWFXzz0e39Xtx2neNb0xqegiQmZCS01p3cqsMRgSu7l7SqYaRjm2HkZy2K/p+jr/GBAyMqbr/QxFm5MtbQ3epoCCGBQKB9n5oKhMYA+LurPlrygmfYLw4wA=
message.center.export.center.account.id=64
## upload
qiankun.upload.profile=st
###upload by upc appId
qiankun.upload.appId=xm-yp-upc-0018
xiaomi.mall.authKey=tGECDh5VI0hWAPkl2JSxPGUsQK9qd897cTI5Zwf3eCnQW3fPVeWJ6JCQDoTYA0upRTzrw5FqbgC0BNDCnJAjAIVmHGBLNqJTs2fBIyoWIDlT8x0H2I/8YEBQScD1c+0ATp18nBmgN2LgYFNBSNr4hldOQo2TV15GfdveKNZKrAA==
xiaomi.mall.host=http://comment.test.b2c.srv

## converged cloud for mail
mail.address=https://staging-mail.api.xiaomi.net
mail.type=45

dubbo.group.maindata=staging

data.go.url=http://datago-be.pre.mi.com
threadpool.config=find:test
MiApi.autoUpdate=true

upload.api.url=https://nr-upload.test.mi.com/
upload.api.appkey=GDD0AvWUxxsjSNYjlHv836cHEjHAxNaHwyHQpN4tfw1se9eQTbnBCKv2YsxNKdBW48sYEn/4Xmxkk0Rlu/EPZ+YY8Pom/xgQWQ4UOM50Rwmweu7KFnin+BgU5wey4sx2Ea3S1OoLlKHoLRIx9ZUA
upload.api.projectId=18

#upload
dubbo.nr-upload-center.appId=xm-yp-upc-0787
dubbo.nr-upload-center.appKey=751386489dd3a93787db3eb5bb103f7d
dubbo.nr-upload-center.projectId=787
dubbo.nr-upload-center.url=https://nr-upload.test.mi.com

dubbo.group.upload=staging

#X5\u534F\u8BAE\u63A5\u53E3\u7B7E\u540D
upc.sign-key=GDDLQ1uEaAXRiCeFOa5qASrB5DAze1ZGLXCT2IeM5/OeSQ+tZl93GaRJOT4j5NK7o4YYEost7fxQp0Patiihktr56LiP/xgQmYLHegg3T+GgqiLQ+EkbDRgUrUuuQDa5xgIkGkhPcwCSpWd+D90A
#\u7CFB\u7EDFid
upc.appId=xm-yp-upc-0018

dubbo.group.orderId=staging
dubbo.group.cis=staging
dubbo.group.store=staging
dubbo.group.eiam=staging
dubbo.group.userquery=staging

car.label.tagDefId=530

user.query.access.key=car-mrs
user.query.secret.key=GCDSJpE5u3bg+petEONXFfG3lZ6J+nvVYNtgARg59l+SPBgStVAAH3rARdiOMzuuEg1OOyP/GBCt2QN3By5HvpO5UerI8v6gGBSZz+zE8wENWzmvLMr74bRRLSWNWgA=

rocketmq.nameserver=staging-cnbj2-rocketmq.namesrv.api.xiaomi.net:9876
car.order.status.change.topic=nr_message_car_mrs_order_status_change_topic
car.complaint.manage.consumer=complaint_manage_consumer
rocketmq.accessKey=GCCG5Uwm+mmUaVwBW0jfczsOa4/xlJ6kMcBrVUyrMjkUnhgSXtR9flsNT429JSpyAQlC3l//GBBkBccRXQBFa7DqhLs24Dk1GBQzKpohJJgT1wPRVgQOQPBe5wdS4wA=
rocketmq.secretKey=GDBTlz+/H9dYHlDz6u/F3+M9oqKygpPg4UPELyRWZ2jM1/L+J1Ppk7ktgrLJPFvYqK8YEu9d6fFbc0h7hdU4a5WwwufY/xgQ8Dk6YylrTGu8m4dHbZRJnRgUir3GtGCNg/wm2PGwsTutyooMSe8A

rocketmq.topic.nr_car_soc_operate_work_order=nr_car_soc_operate_work_order
rocketmq.producer.group=car_complaint_manage_producer_group

car.org.change.topic=store_digitization_car_test

kc.sid=proretail-test

proretail.keycenter.config.sid=proretail-test
proretail.keycenter.config.host=kcagent.sec.xiaomi.com
proretail.keycenter.auto.decrypt.log.open=true
proretail.keycenter.auto.decrypt.youpinlog.open=true
pc.main.car.maintenance.url=https://v-be.test.mi.com/main-car-maintenance/
pc.main.customer.service.url=https://kefu.test.v.mi.com/main-customer-service/
lark.app.id=cli_a774b5679c38d063
lark.app.secret=GDBWOQ5BtZQA59Qq7I-nwFVZkv40MVlvlPBjZxkfWnxVD2v9sN9qIIuWFwTyXDUY9eIYEqESu9Agk0IXgJ03ZZTRI7xM_xgQekmXHbM65IkAlotdj7g3oxgUWD6kP54cEFnyHT20EN-wOROfnQMlABIA
#BPM??
dubbo.nr-bpm.appId=
dubbo.nr-bpm.appKey=
deliverHost=https://v.test.mi.com
